In [1]:
import nltk
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
import pandas as pd
from nltk.stem.snowball import SnowballStemmer
import string
from string import digits
nltk.download('punkt')
nltk.download('stopwords')
import xgboost as xgb
import numpy as np
import sklearn as sk

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Radames\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Radames\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


c:\users\radames\appdata\local\programs\python\python36\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
df_train = pd.read_csv("../data/train.csv")
# 3 столбца - id, text, author
df_train.head(n=3)

id                                               text author
0  id26305  This process, however, afforded me no means of...    EAP
1  id17569  It never once occurred to me that the fumbling...    HPL
2  id11008  In his left hand was a gold snuff box, from wh...    EAP

In [3]:
remove_digits = str.maketrans('', '', digits)
def tokenize_stem(file_text):
    #firstly let's apply nltk tokenization
    file_text = file_text.translate(remove_digits)
    
    tokens = nltk.word_tokenize(file_text)

    #let's delete punctuation symbols
    tokens = [i for i in tokens if ( i not in string.punctuation )]

    #deleting stop_words
    stop_words = stopwords.words('english')
    tokens = [i for i in tokens if ( i not in stop_words )]

    #cleaning words
    stemmer = SnowballStemmer("english")
    
    tokens = [stemmer.stem(i) for i in tokens]

    return tokens

In [4]:
df_train['cleaned_text'] = df_train.text.apply(tokenize_stem)
df_train['cleaned_text_string'] = df_train.cleaned_text.apply(' '.join)
df_train.head(n=3)

id                                               text author  \
0  id26305  This process, however, afforded me no means of...    EAP   
1  id17569  It never once occurred to me that the fumbling...    HPL   
2  id11008  In his left hand was a gold snuff box, from wh...    EAP   

                                        cleaned_text  \
0  [this, process, howev, afford, mean, ascertain...   
1     [it, never, occur, fumbl, might, mere, mistak]   
2  [in, left, hand, gold, snuff, box, caper, hill...   

                                 cleaned_text_string  
0  this process howev afford mean ascertain dimen...  
1             it never occur fumbl might mere mistak  
2  in left hand gold snuff box caper hill cut man...

In [5]:
df_train['length']=df_train['cleaned_text_string'].apply(len)
df_train.head(n=3)

id                                               text author  \
0  id26305  This process, however, afforded me no means of...    EAP   
1  id17569  It never once occurred to me that the fumbling...    HPL   
2  id11008  In his left hand was a gold snuff box, from wh...    EAP   

                                        cleaned_text  \
0  [this, process, howev, afford, mean, ascertain...   
1     [it, never, occur, fumbl, might, mere, mistak]   
2  [in, left, hand, gold, snuff, box, caper, hill...   

                                 cleaned_text_string  length  
0  this process howev afford mean ascertain dimen...     145  
1             it never occur fumbl might mere mistak      38  
2  in left hand gold snuff box caper hill cut man...     116

In [6]:
df_hpl=df_train[df_train['author']=='HPL']
df_hpl.describe()

length
count  5635.000000
mean     93.395386
std      51.075096
min       7.000000
25%      58.000000
50%      85.000000
75%     118.000000
max     561.000000

In [7]:
df_eap=df_train[df_train['author']=='EAP']
df_eap.describe()

length
count  7900.000000
mean     81.543165
std      60.100183
min       5.000000
25%      40.000000
50%      66.000000
75%     106.000000
max     925.000000

In [8]:
df_mws=df_train[df_train['author']=='MWS']
df_mws.describe()

length
count  6044.000000
mean     86.124586
std      71.976281
min       4.000000
25%      48.000000
50%      74.000000
75%     108.000000
max    2715.000000

In [9]:
wordset=set()

In [10]:
#делаю сет со всеми словами
for i in df_train.index:
    wordset |= set(df_train['cleaned_text'][i])
wordlist=list(wordset)

In [11]:
#делаю фрейм со словами
df_word=pd.DataFrame(columns=["word", "mws", "eap", "hpl", "all"])
df_word["word"]=wordlist
df_word["mws"]=0
df_word["eap"]=0
df_word["hpl"]=0
df_word["all"]=0
df_word.head()

word  mws  eap  hpl  all
0      monoton    0    0    0    0
1  nondescript    0    0    0    0
2     endureth    0    0    0    0
3       volunt    0    0    0    0
4         inur    0    0    0    0

In [12]:
# как мы будем эту штуку правильнее делать (возможно это жуткий костыль), я хз
# сначала создаем словарь где ключ - уникальное слово, а значение - его порядковый номер
# затем создаем разреженную матрицу, которую заполняем в зависимости от порядковых номеров 
word_dict = {}



In [13]:
#делаю сет со всеми словами
# и сразу заготовку под шапку(потом увидишь зачем)
counter = 0
head = []

for wordlist in df_train['cleaned_text']:
    for word in wordlist:
        if word not in word_dict:
            head.append(word)
            word_dict[word] = counter
            counter += 1


In [14]:
# видоизменять колонки в pandas руками по одному значению в строке или столбце - очень плохая идея
# колонка это numpy.ndarray, а значит при каждой итерации она будет пересоздаваться
# что угробит производительность
# делаем значит так. считаем где сколько и где встречались отдельные слова, затем создаем строку за строкой для 
# каждого предложения

list_of_lists = []

for wordlist in df_train['cleaned_text']:
    row = [0 for i in range(len(word_dict))]
    for word in wordlist:
        row[word_dict[word]] += 1
    list_of_lists.append(row)



In [15]:
print(len(list_of_lists))

19579


In [16]:
# ... и для того чтобы посмотреть встречаемость того или иного слова по авторам добавим такую колонку

count_frame = pd.DataFrame(list_of_lists)
count_frame['author'] = df_train['author']



In [17]:
# ... и теперь нормальную шапку делаем

count_frame.columns = head + ['author']


In [18]:
print(count_frame.head())

   this  process  howev  afford  mean  ascertain  dimens  dungeon  i  might  \
0     1        1      1       1     1          1       1        1  2      1   
1     0        0      0       0     0          0       0        0  0      1   
2     0        0      0       0     0          0       0        0  0      0   
3     0        0      0       0     0          0       0        0  0      0   
4     0        0      0       0     0          0       0        0  0      0   

    ...    aegidus  burr  bentley  waltzer  binder  brusqueri  adriat  ancona  \
0   ...          0     0        0        0       0          0       0       0   
1   ...          0     0        0        0       0          0       0       0   
2   ...          0     0        0        0       0          0       0       0   
3   ...          0     0        0        0       0          0       0       0   
4   ...          0     0        0        0       0          0       0       0   

   agir  author  
0     0     EAP  
1 

In [19]:
# Пока объединим все, потом может быть будем использовать
col=list(count_frame.columns)
col[-1]='author_name'
count_frame.columns=col
pivot_col=pd.pivot_table(count_frame, aggfunc=np.sum, values=col, index=['author_name'])

In [20]:
#Убираем лишние слова, которые не учли раньше
col=list(pivot_col.columns)
col2=[string for string in col if (string[0]!='"' and string[0]!="'"
                                  and string[0]!='.' and string[0]!='`'
                                   and len(string)>3 and '.' not in string)]
col=[]
pivot_col=pivot_col[col2]
pivot_col.head()

aaem  aback  abaft  abandon  abaout  abas  abash  abat  abbey  \
author_name                                                                  
EAP             1      2      0       22       0     2      1     2      3   
HPL             0      0      0       17      24     0      1     3      0   
MWS             0      0      1        9       0     0      0     1      2   

             abbrevi  ...    æmilianus  æneid  ærial  æronaut  ærostat  \
author_name           ...                                                
EAP                2  ...            0      0      1        3        1   
HPL                0  ...            2      1      0        0        0   
MWS                0  ...            0      0      0        0        0   

             æschylus  élite  émeut  οἶδα  υπνος  
author_name                                       
EAP                 1      1      1     0      0  
HPL                 0      0      0     2      1  
MWS                 0      0      0     0      0  

[3 rows x 14351 columns]

In [21]:
#Create pivot
pivot_col=pivot_col.append(pivot_col.sum(), ignore_index=True)
pivot_col.index=['EAP', 'HPL', 'MWS', 'SUMA']
pivot_col.head()

aaem  aback  abaft  abandon  abaout  abas  abash  abat  abbey  abbrevi  \
EAP      1      2      0       22       0     2      1     2      3        2   
HPL      0      0      0       17      24     0      1     3      0        0   
MWS      0      0      1        9       0     0      0     1      2        0   
SUMA     1      2      1       48      24     2      2     6      5        2   

      ...    æmilianus  æneid  ærial  æronaut  ærostat  æschylus  élite  \
EAP   ...            0      0      1        3        1         1      1   
HPL   ...            2      1      0        0        0         0      0   
MWS   ...            0      0      0        0        0         0      0   
SUMA  ...            2      1      1        3        1         1      1   

      émeut  οἶδα  υπνος  
EAP       1     0      0  
HPL       0     2      1  
MWS       0     0      0  
SUMA      1     2      1  

[4 rows x 14351 columns]

In [22]:
summa=[pivot_col.loc['EAP'].sum(), pivot_col.loc['HPL'].sum(), 
       pivot_col.loc['MWS'].sum(), pivot_col.loc['SUMA'].sum()]
pivot_col['summa']=summa
pivot_col.head()

aaem  aback  abaft  abandon  abaout  abas  abash  abat  abbey  abbrevi  \
EAP      1      2      0       22       0     2      1     2      3        2   
HPL      0      0      0       17      24     0      1     3      0        0   
MWS      0      0      1        9       0     0      0     1      2        0   
SUMA     1      2      1       48      24     2      2     6      5        2   

       ...    æneid  ærial  æronaut  ærostat  æschylus  élite  émeut  οἶδα  \
EAP    ...        0      1        3        1         1      1      1     0   
HPL    ...        1      0        0        0         0      0      0     2   
MWS    ...        0      0        0        0         0      0      0     0   
SUMA   ...        1      1        3        1         1      1      1     2   

      υπνος   summa  
EAP       0   87765  
HPL       1   74269  
MWS       0   73160  
SUMA      1  235194  

[4 rows x 14352 columns]

In [23]:
# Create probability of author text knowing that a word was used
pivot_part=pivot_col
pivot_part.loc['EAP']=pivot_col.loc['EAP']/pivot_col.loc['SUMA']
pivot_part.loc['HPL']=pivot_col.loc['HPL']/pivot_col.loc['SUMA']
pivot_part.loc['MWS']=pivot_col.loc['MWS']/pivot_col.loc['SUMA']
pivot_part=pivot_part.loc[['EAP', 'HPL', 'MWS']]
# Delete unique words
pivot_part=pivot_part.loc[:, (pivot_part!=1).all(axis=0)]
pivot_part.head()

abandon  abash      abat  abbey     abdic     aberr     abhor    abhorr  \
EAP  0.458333    0.5  0.333333    0.6  0.142857  0.166667  0.058824  0.111111   
HPL  0.354167    0.5  0.500000    0.0  0.000000  0.666667  0.235294  0.555556   
MWS  0.187500    0.0  0.166667    0.4  0.857143  0.166667  0.705882  0.333333   

         abil    abject    ...      younger  youngest      your     youth  \
EAP  0.789474  0.333333    ...     0.272727       0.2  0.534884  0.101562   
HPL  0.052632  0.000000    ...     0.000000       0.4  0.069767  0.429688   
MWS  0.157895  0.666667    ...     0.727273       0.4  0.395349  0.468750   

         zeal  zenith  zest  zigzag      zone     summa  
EAP  0.117647     0.4   0.2     0.4  0.666667  0.373160  
HPL  0.470588     0.6   0.2     0.6  0.333333  0.315778  
MWS  0.411765     0.0   0.6     0.0  0.000000  0.311062  

[3 rows x 6619 columns]

In [24]:
# It will be easier to work this way
eap_dict=pivot_part.loc['EAP'].to_dict()
hpl_dict=pivot_part.loc['HPL'].to_dict()
mws_dict=pivot_part.loc['MWS'].to_dict()
eap_dict['word']

0.44859813084112149

In [25]:
# Create author score 
def ind_val_eap(listn):
    quant=0
    for word in listn:
        try:
            quant+=eap_dict[word]
        except KeyError:
            quant+=0
    return quant

def ind_val_hpl(listn):
    quant=0
    for word in listn:
        try:
            quant+=hpl_dict[word]
        except KeyError:
            quant+=0
    return quant

def ind_val_mws(listn):
    quant=0
    for word in listn:
        try:
            quant+=mws_dict[word]
        except KeyError:
            quant+=0
    return quant

In [26]:
# Add index of author
df_train['mws_index']=df_train['cleaned_text'].apply(ind_val_mws)/df_train['length']
df_train['eap_index']=df_train['cleaned_text'].apply(ind_val_eap)/df_train['length']
df_train['hpl_index']=df_train['cleaned_text'].apply(ind_val_hpl)/df_train['length']
df_train.head(n=3)

id                                               text author  \
0  id26305  This process, however, afforded me no means of...    EAP   
1  id17569  It never once occurred to me that the fumbling...    HPL   
2  id11008  In his left hand was a gold snuff box, from wh...    EAP   

                                        cleaned_text  \
0  [this, process, howev, afford, mean, ascertain...   
1     [it, never, occur, fumbl, might, mere, mistak]   
2  [in, left, hand, gold, snuff, box, caper, hill...   

                                 cleaned_text_string  length  mws_index  \
0  this process howev afford mean ascertain dimen...     145   0.035935   
1             it never occur fumbl might mere mistak      38   0.035860   
2  in left hand gold snuff box caper hill cut man...     116   0.026900   

   eap_index  hpl_index  
0   0.074388   0.034504  
1   0.060980   0.034739  
2   0.047832   0.037337

In [27]:
#Transform authors' names to numeric
df_train['author']=df_train['author'].astype('category')
df_train['author2']=df_train['author'].cat.codes
# Create different features 
df_train['mwseap']=df_train['mws_index']/df_train['eap_index']
df_train['eaphpl']=df_train['eap_index']/df_train['hpl_index']
df_train['hplmws']=df_train['hpl_index']/df_train['mws_index']
df_train['mws']=df_train['mws_index']*df_train['length']
df_train['eap']=df_train['eap_index']*df_train['length']
df_train['hpl']=df_train['hpl_index']*df_train['length']
df_train.head(n=3)
mid = df_train['author2']
df_train.drop(labels=['author2'], axis=1,inplace = True)
df_train.insert(0, 'author2', mid)
df_train.head()

author2       id                                               text author  \
0        0  id26305  This process, however, afforded me no means of...    EAP   
1        1  id17569  It never once occurred to me that the fumbling...    HPL   
2        0  id11008  In his left hand was a gold snuff box, from wh...    EAP   
3        2  id27763  How lovely is spring As we looked from Windsor...    MWS   
4        1  id12958  Finding nothing else, not even gold, the Super...    HPL   

                                        cleaned_text  \
0  [this, process, howev, afford, mean, ascertain...   
1     [it, never, occur, fumbl, might, mere, mistak]   
2  [in, left, hand, gold, snuff, box, caper, hill...   
3  [how, love, spring, as, look, windsor, terrac,...   
4  [find, noth, els, even, gold, superintend, aba...   

                                 cleaned_text_string  length  mws_index  \
0  this process howev afford mean ascertain dimen...     145   0.035935   
1             it never occur fumbl might mere mistak      38   0.035860   
2  in left hand gold snuff box caper hill cut man...     116   0.026900   
3  how love spring as look windsor terrac sixteen...     144   0.071850   
4  find noth els even gold superintend abandon at...     102   0.036859   

   eap_index  hpl_index    mwseap    eaphpl    hplmws        mws        eap  \
0   0.074388   0.034504  0.483071  2.155927  0.960185   5.210565  10.786330   
1   0.060980   0.034739  0.588060  1.755405  0.968726   1.362682   2.317251   
2   0.047832   0.037337  0.562388  1.281102  1.387971   3.120422   5.548524   
3   0.033438   0.033601  2.148730  0.995150  0.467659  10.346342   4.815096   
4   0.056661   0.043735  0.650516  1.295536  1.186568   3.759590   5.779399   

        hpl  
0  5.003105  
1  1.320066  
2  4.331054  
3  4.838562  
4  4.461011

In [33]:
# Create data set
ds_train=df_train.values
X=ds_train[:, 6:]
Y=ds_train[:, 0]
seed=7
test_size=0.3
X_train, X_test, y_train, y_test = sk.model_selection.train_test_split(X,Y, test_size=test_size, random_state=seed)

In [34]:
# fit model
xg_train=xgb.DMatrix(X_train, label=y_train)
xg_test=xgb.DMatrix(X_test, label=y_test)
param={}
param['objective'] = 'multi:softmax'
param['eta'] = 0.3
param['max_depth'] = 3
param['silent'] = 1
param['nthread'] = 4
param['num_class'] = 3
watchlist = [(xg_train, 'train'), (xg_test, 'test')]
num_round = 5
bst = xgb.train(param, xg_train, num_round, watchlist)
# get prediction
pred = bst.predict(xg_test)
error_rate = np.sum(pred != y_test) / y_test.shape[0]
print('Test error using softmax = {}'.format(error_rate))

[0]	train-merror:0.175775	test-merror:0.180626
[1]	train-merror:0.1695	test-merror:0.173817
[2]	train-merror:0.168625	test-merror:0.170582
[3]	train-merror:0.165122	test-merror:0.167348
[4]	train-merror:0.165122	test-merror:0.168029
Test error using softmax = 0.16802860061287028


In [35]:
# do the same thing again, but output probabilities
param['objective'] = 'multi:softprob'
bstp = xgb.train(param, xg_train, num_round, watchlist)
# Note: this convention has been changed since xgboost-unity
# get prediction, this is in 1D array, need reshape to (ndata, nclass)
pred_prob = bstp.predict(xg_test).reshape(y_test.shape[0], 3)
pred_label = np.argmax(pred_prob, axis=1)
error_rate = np.sum(pred_label != y_test) / y_test.shape[0]
print('Test error using softprob = {}'.format(error_rate))

[0]	train-merror:0.175775	test-merror:0.180626
[1]	train-merror:0.1695	test-merror:0.173817
[2]	train-merror:0.168625	test-merror:0.170582
[3]	train-merror:0.165122	test-merror:0.167348
[4]	train-merror:0.165122	test-merror:0.168029
Test error using softprob = 0.16802860061287028


In [36]:
df_test = pd.read_csv("../data/test.csv")
df_test.head(n=3)

id                                               text
0  id02310  Still, as I urged our leaving Ireland with suc...
1  id24541  If a fire wanted fanning, it could readily be ...
2  id00134  And when they had broken down the frail door t...

In [37]:
df_test['cleaned_text'] = df_test.text.apply(tokenize_stem)
df_test['cleaned_text_string'] = df_test.cleaned_text.apply(' '.join)
df_test.head(n=3)


id                                               text  \
0  id02310  Still, as I urged our leaving Ireland with suc...   
1  id24541  If a fire wanted fanning, it could readily be ...   
2  id00134  And when they had broken down the frail door t...   

                                        cleaned_text  \
0  [still, i, urg, leav, ireland, inquietud, impa...   
1  [if, fire, want, fan, could, readili, fan, new...   
2  [and, broken, frail, door, found, two, clean, ...   

                                 cleaned_text_string  
0  still i urg leav ireland inquietud impati fath...  
1  if fire want fan could readili fan newspap gov...  
2  and broken frail door found two clean pick hum...

In [38]:
df_test['length']=df_test['cleaned_text_string'].apply(len)
df_test.head(n=3)

id                                               text  \
0  id02310  Still, as I urged our leaving Ireland with suc...   
1  id24541  If a fire wanted fanning, it could readily be ...   
2  id00134  And when they had broken down the frail door t...   

                                        cleaned_text  \
0  [still, i, urg, leav, ireland, inquietud, impa...   
1  [if, fire, want, fan, could, readili, fan, new...   
2  [and, broken, frail, door, found, two, clean, ...   

                                 cleaned_text_string  length  
0  still i urg leav ireland inquietud impati fath...      67  
1  if fire want fan could readili fan newspap gov...     181  
2  and broken frail door found two clean pick hum...     114

In [39]:
df_test['mws_index']=df_test['cleaned_text'].apply(ind_val_mws)/df_test['length']
df_test['eap_index']=df_test['cleaned_text'].apply(ind_val_eap)/df_test['length']
df_test['hpl_index']=df_test['cleaned_text'].apply(ind_val_hpl)/df_test['length']
df_test.head(n=3)
df_test['mwseap']=df_test['mws_index']/df_train['eap_index']
df_test['eaphpl']=df_test['eap_index']/df_train['hpl_index']
df_test['hplmws']=df_test['hpl_index']/df_train['mws_index']
df_test['mws']=df_test['mws_index']*df_train['length']
df_test['eap']=df_test['eap_index']*df_train['length']
df_test['hpl']=df_test['hpl_index']*df_train['length']
df_test.head(n=3)

id                                               text  \
0  id02310  Still, as I urged our leaving Ireland with suc...   
1  id24541  If a fire wanted fanning, it could readily be ...   
2  id00134  And when they had broken down the frail door t...   

                                        cleaned_text  \
0  [still, i, urg, leav, ireland, inquietud, impa...   
1  [if, fire, want, fan, could, readili, fan, new...   
2  [and, broken, frail, door, found, two, clean, ...   

                                 cleaned_text_string  length  mws_index  \
0  still i urg leav ireland inquietud impati fath...      67   0.071473   
1  if fire want fan could readili fan newspap gov...     181   0.035932   
2  and broken frail door found two clean pick hum...     114   0.027486   

   eap_index  hpl_index    mwseap    eaphpl    hplmws        mws       eap  \
0   0.036315   0.026541  0.960801  1.052477  0.738585  10.363516  5.265652   
1   0.062884   0.039306  0.589239  1.810197  1.096092   1.365414  2.389580   
2   0.055142   0.057723  0.574635  1.476892  2.145808   3.188375  6.396501   

        hpl  
0  3.848444  
1  1.493625  
2  6.695826

In [40]:
ds_test=df_test.values

In [41]:
x_t=ds_test[:, 4:]
y_t=ds_test[:, 0]
xg_t=xgb.DMatrix(x_t)
pred_prob = bstp.predict(xg_t).reshape(y_t.shape[0], 3)
pred_label = np.argmax(pred_prob, axis=1)

In [42]:
print(pred_prob)

[[ 0.17210871  0.2052936   0.62259769]
 [ 0.79707724  0.09948414  0.10343868]
 [ 0.78167707  0.12520461  0.09311831]
 ..., 
 [ 0.75250143  0.11132803  0.13617054]
 [ 0.15438901  0.12317174  0.72243923]
 [ 0.46898594  0.38881034  0.14220369]]


In [43]:
export=pd.DataFrame(pred_prob)
export.insert(loc=0, column='id', value=y_t)
export.columns=['id','EAP', 'HPL', 'MWS']
export.head()

id       EAP       HPL       MWS
0  id02310  0.172109  0.205294  0.622598
1  id24541  0.797077  0.099484  0.103439
2  id00134  0.781677  0.125205  0.093118
3  id27757  0.739636  0.130136  0.130229
4  id04081  0.790499  0.108423  0.101077

In [44]:
len(export)

8392

In [45]:
export.to_csv(path_or_buf="../data/export.csv", index=False)